export const homeObjOne = {
  id: "smartContract",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "What is Leet Code System is  all about?",
  headLine: "Design Highly Efficient  Full Stack Web Application for online coding platform",
  description:"LeetCode is a leading online platform for coding practice, offering a vast collection of problems that cover algorithms, data structures, databases, and system design. It allows users to improve their coding skills, prepare for technical interviews, and compete with a global community through contests and challenges in various programming languages.",
  buttonLabel: "Get Started",
  imgStart: false,
  img: "https://dm-frontend.s3.amazonaws.com/sme-journey/svg-1.svg",
  alt: "car",
  dark: false,
  primary: true,
  darkText: false,
};
